# Parte 8 | Deep Learning

In [1]:
# Importing the libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Seção 31 | Artificial Neural Network (ANN)

##### Part 1 - Setting up

In [2]:
dss31 = pd.read_csv('C:\\Users\\rafae\\Dropbox\\Data_Science\\Cursos\\A_to_Z\\Part 8 - Deep Learning\\Section 39 - Artificial Neural Networks (ANN)\\Churn_Modelling.csv')

In [3]:
dss31.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X = dss31.iloc[:, 3:13].values
y = dss31.iloc[:, 13].values

In [5]:
# Encoding categorical data

from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder_X_1 = LabelEncoder()
X[:,1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:,2] = labelencoder_X_2.fit_transform(X[:, 2])

onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

In [6]:
# Splitting the dataset into the Training set and Test set

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [7]:
# Feature scaling

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train) 
X_test =  sc.transform(X_test)

In [8]:
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ..., 
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

##### Part 2 - Making the ANN

In [9]:
# Importing the Keras libraries and packages

import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [10]:
# Initialising the ANN

classifier = Sequential()

In [11]:
# Adding the input layer and the first hidden layer

# How manny nodes to include in the hidden layer? The $1 million dollar question -- there is no rule of thumb -- experiment.
# A good starting point is the avarage number of the input layer and the output layer.

classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))

C:\Users\rafae\Anaconda3\envs\rafael\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  


In [12]:
# Adding the second hidden layer

classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))

C:\Users\rafae\Anaconda3\envs\rafael\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until


In [13]:
# Adding the output layer

classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

C:\Users\rafae\Anaconda3\envs\rafael\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until


In [14]:
# Compiling the ANN

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Adam is a type of stochastic gradient descent

In [15]:
# Fitting the ANN to the Training set

classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

C:\Users\rafae\Anaconda3\envs\rafael\lib\site-packages\keras\models.py:942: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/100
8000/8000 [==============================] - 2s 277us/step - loss: 0.4879 - acc: 0.7966
Epoch 2/100
8000/8000 [==============================] - 2s 189us/step - loss: 0.4071 - acc: 0.8124
Epoch 3/100
8000/8000 [==============================] - 2s 191us/step - loss: 0.3794 - acc: 0.8355
Epoch 4/100
8000/8000 [==============================] - 2s 209us/step - loss: 0.3603 - acc: 0.8526
Epoch 5/100
8000/8000 [==============================] - 2s 197us/step - loss: 0.3515 - acc: 0.8564
Epoch 6/100
8000/8000 [==============================] - 2s 200us/step - loss: 0.3477 - acc: 0.8609
Epoch 7/100
8000/8000 [==============================] - 2s 193us/step - loss: 0.3453 - acc: 0.8572
Epoch 8/100
8000/8000 [==============================] - 2s 201us/step - loss: 0.3447 - acc: 0.8604
Epoch 9/100
8000/8000 [==============================] - 2s 196us/step - loss: 0.3432 - acc: 0.8596
Epoch 10/100
8000/8000 [==============================] - 2s 194us/step - loss: 0.3420 - acc: 0.8606

8000/8000 [==============================] - 2s 205us/step - loss: 0.3339 - acc: 0.8639
Epoch 82/100
8000/8000 [==============================] - 2s 210us/step - loss: 0.3340 - acc: 0.8657
Epoch 83/100
8000/8000 [==============================] - 2s 212us/step - loss: 0.3338 - acc: 0.8626
Epoch 84/100
8000/8000 [==============================] - 2s 210us/step - loss: 0.3343 - acc: 0.8629
Epoch 85/100
8000/8000 [==============================] - 2s 208us/step - loss: 0.3342 - acc: 0.8639
Epoch 86/100
8000/8000 [==============================] - 2s 211us/step - loss: 0.3344 - acc: 0.8641
Epoch 87/100
8000/8000 [==============================] - 2s 224us/step - loss: 0.3342 - acc: 0.8632
Epoch 88/100
8000/8000 [==============================] - 2s 195us/step - loss: 0.3346 - acc: 0.8637
Epoch 89/100
8000/8000 [==============================] - 2s 207us/step - loss: 0.3340 - acc: 0.8631
Epoch 90/100
8000/8000 [==============================] - 2s 213us/step - loss: 0.3342 - acc: 0.8635
Epo

##### Part 3 - Making the predictions and evaluating the model

In [16]:
# Predicting the Test set results

y_pred = classifier.predict(X_test)

In [17]:
y_pred

array([[ 0.31195754],
       [ 0.3014726 ],
       [ 0.17673841],
       ..., 
       [ 0.29019096],
       [ 0.18440339],
       [ 0.24251905]], dtype=float32)

In [18]:
y_pred = (y_pred > 0.5)

In [19]:
# Making the confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1514,   81],
       [ 200,  205]], dtype=int64)

In [22]:
(1514 + 205)/2000

0.8595

### Seção 32 | Convolutional Neural Networks

##### Part 1 - Building the CNN

In [23]:
# Importing the Keras libraries and packages

# Each package corresponds to one step of the construction of the CNN

import keras
from keras.models import Sequential
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense

In [24]:
# Initialising the CNN

classifier = Sequential()

In [25]:
# Step 1 - Convolution

classifier.add(Convolution2D(32, 3, 3, input_shape = (64, 64, 3), activation = 'relu'))

C:\Users\rafae\Anaconda3\envs\rafael\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), input_shape=(64, 64, 3..., activation="relu")`
  This is separate from the ipykernel package so we can avoid doing imports until


In [26]:
# Step 2 - Pooling

classifier.add(MaxPooling2D(pool_size = (2,2)))

In [27]:
# Step 3 - Flattening

classifier.add(Flatten())

In [28]:
# Step 4 - Full connection

classifier.add(Dense(output_dim = 128, activation = 'relu'))
classifier.add(Dense(output_dim = 1, activation = 'sigmoid'))

C:\Users\rafae\Anaconda3\envs\rafael\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=128)`
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\rafae\Anaconda3\envs\rafael\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1)`
  after removing the cwd from sys.path.


In [29]:
# Compiling the CNN

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

##### Part 2 - Building the CNN

In [35]:
# https://keras.io/preprocessing/image/

from keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(
        rescale=1./255,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True)

test_datagen = ImageDataGenerator(rescale=1./255)

training_set = train_datagen.flow_from_directory('C:\\Users\\rafae\\GitHub\\udemy_machinelearning_a_to_z\\data\\Convolutional_Neural_Networks\\dataset\\training_set',
                                                target_size=(64, 64),
                                                batch_size=32,
                                                class_mode='binary')

test_set = test_datagen.flow_from_directory('C:\\Users\\rafae\\GitHub\\udemy_machinelearning_a_to_z\\data\\Convolutional_Neural_Networks\\dataset\\test_set',
                                            target_size=(64, 64),
                                            batch_size=32,
                                            class_mode='binary')

classifier.fit_generator(training_set,
                    steps_per_epoch=8000,
                    epochs=25,
                    validation_data=test_set,
                    validation_steps=2000)

Found 8000 images belonging to 2 classes.
Found 2000 images belonging to 2 classes.
Epoch 1/25
8000/8000 [==============================] - 2683s 335ms/step - loss: 0.3445 - acc: 0.8431 - val_loss: 0.8036 - val_acc: 0.7602
Epoch 2/25
8000/8000 [==============================] - 2425s 303ms/step - loss: 0.1234 - acc: 0.9533 - val_loss: 1.1727 - val_acc: 0.7511
Epoch 3/25
8000/8000 [==============================] - 2428s 303ms/step - loss: 0.0678 - acc: 0.9761 - val_loss: 1.4013 - val_acc: 0.7654
Epoch 4/25
8000/8000 [==============================] - 2194s 274ms/step - loss: 0.0473 - acc: 0.9840 - val_loss: 1.6247 - val_acc: 0.7601
Epoch 5/25
8000/8000 [==============================] - 2170s 271ms/step - loss: 0.0382 - acc: 0.9873 - val_loss: 1.8335 - val_acc: 0.7464
Epoch 6/25
8000/8000 [==============================] - 2779s 347ms/step - loss: 0.0320 - acc: 0.9895 - val_loss: 1.7399 - val_acc: 0.7680
Epoch 7/25
8000/8000 [==============================] - 2319s 290ms/step - loss: 0

In [ ]:
# Adding 1 more layer to improve the accuracy:

#classifier_deeper = Sequential()
#classifier_deeper.add(Convolution2D(32, 3, 3, input_shape = (64, 64, 3), activation = 'relu'))
#classifier_deeper.add(MaxPooling2D(pool_size = (2,2)))

## Adding a 2nd convolutional layer
#classifier_deeper.add(Convolution2D(32, 3, 3, activation = 'relu'))
#classifier_deeper.add(MaxPooling2D(pool_size = (2,2)))

#classifier.add(Flatten())
#classifier.add(Dense(output_dim = 128, activation = 'relu'))
#classifier.add(Dense(output_dim = 1, activation = 'sigmoid'))
#classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

#from keras.preprocessing.image import ImageDataGenerator

#train_datagen = ImageDataGenerator(
#        rescale=1./255,
#        shear_range=0.2,
#        zoom_range=0.2,
#        horizontal_flip=True)

#test_datagen = ImageDataGenerator(rescale=1./255)

#training_set = train_datagen.flow_from_directory('C:\\Users\\rafae\\GitHub\\udemy_machinelearning_a_to_z\\data\\Convolutional_Neural_Networks\\dataset\\training_set',
#                                                target_size=(64, 64),
#                                                batch_size=32,
#                                                class_mode='binary')

#test_set = test_datagen.flow_from_directory('C:\\Users\\rafae\\GitHub\\udemy_machinelearning_a_to_z\\data\\Convolutional_Neural_Networks\\dataset\\test_set',
#                                            target_size=(64, 64),
#                                            batch_size=32,
#                                            class_mode='binary')

#classifier.fit_generator(training_set,
#                    steps_per_epoch=8000,
#                    epochs=25,
#                    validation_data=test_set,
#                    validation_steps=2000)